FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=development
ENV PORT=5000

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 5000

CMD ["npm", "run", "dev"]
